#!/usr/bin/env bash

# bash completion for dl-api commandline client

_dl_api()
{
    local cur=${COMP_WORDS[COMP_CWORD]}
    local prev=${COMP_WORDS[COMP_CWORD-1]}

    local first=$(echo $cur | cut -d ':' -f 1)
    local second=$(echo $cur | cut -d ':' -f 2)

    # case "$prev" in
    # esac

    case "$first" in
      "app")
        COMPREPLY=( $( compgen -W "new" -- $second ) )
        return 0
        ;;

      "config")
        COMPREPLY=( $( compgen -W "set remove" -- $second ) )
        return 0
        ;;

      "generate")
        COMPREPLY=( $( compgen -W "observer route schedule seed template" -- $second ) )
        return 0
        ;;

      "db")
        COMPREPLY=( $( compgen -W "seed" -- $second ) )
        return 0
        ;;

      "key")
        COMPREPLY=( $( compgen -W "new" -- $second ) )
        return 0
        ;;

      "schedule")
        COMPREPLY=( $( compgen -W "upload" -- $second ) )
        return 0
        ;;

      "module")
        COMPREPLY=( $( compgen -W "remove upload" -- $second ) )
        return 0
        ;;

    esac

    # completing an option
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $( compgen -W "--app --config --debug --endpoint --help --json --version" -- $cur ) )
      return 0
    fi

    COMPREPLY=( $(compgen -W "app: apps console config: db: generate: key: keys module: modules schedule schedule:" -- $cur) )
    return 0
}

# complete is a bash builtin, but recent versions of ZSH come with a function
# called bashcompinit that will create a complete in ZSH. If the user is in
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
  autoload -U +X bashcompinit && bashcompinit
fi
complete -F _dl_api -o nospace dl-api
